---
title: "Midterm Project"
author: "Yifeng He"
date: "December 4, 2021"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,out.width="0.9\\linewidth",dev="png",fig.align  = 'center')
pacman::p_load(
ggplot2,
knitr,
arm,
data.table,
foreign,
gridExtra,
car,
stringr,
rstan,
rstanarm,
zoo,
dplyr,
tidyr,
magrittr,
hrbrthemes,
ggExtra,
stringr,
viridis,
ggridges,
sure,
fmsb,
ggfortify
)
```


```{r}
attrition <- read.csv('WA_Fn-UseC_-HR-Employee-Attrition.csv', header = T)
head(attrition)

View(attrition)

#convert columns to numeric
cols.num <- c("DistanceFromHome","Age","EnvironmentSatisfaction","MonthlyIncome","TotalWorkingYears","YearsSinceLastPromotion")
attrition[cols.num] <- sapply(attrition[cols.num],as.numeric)
sapply(attrition, class)

attrition$Attrition<-ifelse(attrition$Attrition=="Yes",1,0)

head(attrition)
View(attrition)

#variables I choose
col1 <- c("Age","Distance From Home","Monthly Income","Relationship Satifaction","Years Since Last Promotion")
exp1 <- c("Age of the employee",
          "Distance from company to home",
          "Monthly income of employee",
          "Satisfaction of relationship",
          "Working years since last promotion")
df1 <- cbind(col1, exp1)
colnames(df1) <- c("Variables", "Explanation")
knitr::kable(df1, "pipe")
```

|Variables                  |Explanation                                       |
|:--------------------------|:-------------------------------------------------|
|Age                        |Age of the employee                               |
|Distance From Home         |Distance from company to home                     |
|Environment Satisfaction   |Satisfaction of working environment with 4 levels |
|Monthly Income             |Monthly income of employee                        |
|Total Working Years        |Working years since the first career              |
|Years Since Last Promotion |Working years since last promotion                |



```{r}
#radar chart
attr_try <- attrition[,c(1, 2, 6, 19, 26, 34)]

attr1 <- attr_try[attr_try$Attrition == 1, ]
attr0 <- attr_try[attr_try$Attrition == 0, ]

attri<-as.data.frame(t(cbind(apply(attr1, 2, mean), apply(attr0, 2, mean))))

dfmax <- apply(attr_try, 2, max)
dfmin <- apply(attr_try, 2, min)

attri_dim <- t(cbind(dfmax, dfmin))

attri_final <- rbind(attri_dim, attri)


# Color vector
colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.7,0.5,0.1,0.4) )

# plot with default options:
radarchart(attri_final, 
    pcol=colors_border , pfcol=colors_in , plwd=3 , plty=1,
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
    vlcex=0.8 
    )

# Add a legend
legend(x=1.5, y=1.2, legend = c("Attrition", "Not Attrition"), bty = "n", pch=20 , col=colors_in , cex=0.8, pt.cex=3)

```

```{r}
#group box plots

attri_try1 <- pivot_longer(attr_try, 
                           cols = c(1, 3, 4, 5, 6),
                           names_to = "Factors",
                           values_to = "value"
                           )


log(attri_try1$value)

ggplot(attri_try1, aes(x=Factors, y=log(value), fill=factor(Attrition))) + 
    geom_boxplot()+
  theme(axis.text=element_text(size=5.5, face = "bold"))
```

```{r}
#scatter plots EDA
plot1 <- age_point <- ggplot(data=attrition)+
  geom_point(aes(x=Age,y=Attrition,color=JobRole), alpha = 0.3)+
  geom_smooth(aes(x=Age,y=Attrition,color=JobRole), method = "lm", se = FALSE)+
  theme_ipsum()+
  theme(legend.position = "none")

plot2 <- ggplot(data=attrition)+
  geom_point(aes(x=DistanceFromHome,y=Attrition,color=JobRole), alpha = 0.3)+
  geom_smooth(aes(x=DistanceFromHome,y=Attrition,color=JobRole), method = "lm", se = FALSE)+
  theme_ipsum()+
  theme(legend.position = "none")

plot3 <- ggplot(data=attrition)+
  geom_point(aes(x=MonthlyIncome,y=Attrition,color=JobRole), alpha = 0.3)+
  geom_smooth(aes(x=MonthlyIncome,y=Attrition,color=JobRole), method = "lm", se = FALSE)+
  theme_ipsum()

grid.arrange(plot1, plot2, plot3,
             layout_matrix = rbind(c(1,2),
                                   c(1,2),
                                   c(3,3))
             )

plot4 <- ggplot(data=attrition)+
  geom_point(aes(x=RelationshipSatisfaction,y=Attrition,color=JobRole), alpha = 0.3)+
  geom_smooth(aes(x=TotalWorkingYears,y=Attrition,color=JobRole), method = "lm", se = FALSE)+
  theme_ipsum()+
  theme(legend.position = "none")

plot5 <- ggplot(data=attrition)+
  geom_point(aes(x=YearsSinceLastPromotion,y=Attrition,color=JobRole), alpha = 0.3)+
  geom_smooth(aes(x=YearsSinceLastPromotion,y=Attrition,color=JobRole), method = "lm", se = FALSE)+
  theme_ipsum()

grid.arrange(plot4, plot5,
             layout_matrix = rbind(c(1,1,2,2,2))
             )

ggplot(ggucladata)+aes(x=gre,y=admit,color=admit)+
  theme(legend.position="none")+ 
  theme(axis.text.x = element_text(angle = 25, hjust = 1,size=5))+
  geom_jitter()+
  scale_color_manual(values=c("gray","red"))+
  geom_smooth(aes(group=1),color="blue")

ggplot(attrition)+aes(x=Age,y=Attrition,color=JobRole)+geom_jitter()+geom_smooth(aes(x=Age,y=Attrition,color=JobRole), method = "lm", se = FALSE)

ggplot(data=attrition)+
  geom_point(aes(x=Age,y=Attrition,color=JobRole), alpha = 0.3)+
  theme_ipsum()+
  geom_jitter()+
  geom_smooth(aes(x=Age,y=Attrition,color=JobRole),color="blue")
```

```{r}
#marginal distribution EDA
p <- ggplot(attrition, aes(x=MonthlyIncome,y=Attrition,color=JobRole)) +
        geom_point()

ggMarginal(p, type="density")
ggMarginal(p, type="histogram", fill = "slateblue", xparams = list(bins=10), margins = 'x')
ggMarginal(p, margins = 'x', color="purple", size=4)

#conditional density plot
cdplot(factor(Attrition) ~ Age, data=attrition)

#violin plots
ggplot(attrition, aes(x=JobRole, y=Age, fill=factor(Attrition))) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Violin chart") +
    xlab("")

#boxplot
ggplot(attrition, aes(x=JobRole, y=Age, fill=factor(Attrition))) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.2) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("A boxplot with jitter") +
    xlab("")
```



```{r}
#other EDAs
ggplot(attrition, aes(x = `MonthlyIncome`, y = `JobRole`, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Temp. [F]", option = "C") +
  labs(title = 'Temperatures in Lincoln NE in 2016') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )

ggplot(attrition, aes(x=Age, y=Attrition, size = MonthlyIncome, color = JobRole)) +
    geom_point(alpha=0.7)
```


```{r}
#regression
fit1<-glmer(Attrition~Age+DistanceFromHome+MonthlyIncome+RelationshipSatisfaction+YearsSinceLastPromotion+(1|JobRole) ,data = attrition, family = binomial(link = "logit"))

fix_effect <- round(fixef(fit1), digits = 5)

round(exp(fix_effect) - 1, digits = 5)

ranef(fit1)

coef(fit1)
```


```{r}
b1<-binnedplot(fitted(fit1),resid(fit1, type = "response"))
```




>>>>>>> 9ae135952a0300875076d023246d7beba9bd26ab
